apiVersion: v1
kind: Service
metadata:
  name: svc-deployment
  namespace: default
spec:
  selector:
    app: deployment-12.4
  ports:
  - name: nginx
    port: 9001
    targetPort: 80
  - name: multitool
    port: 9002
    targetPort: 8080
  type: ClusterIP